spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    url: null
    username: null
    password: null
aws:
  client_region: null
  s3_media_bucket_name: null
